
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rafae
 */
public class ControlAcceso extends javax.swing.JFrame {

    /**
     * Creates new form ControlAcceso
     */
        ConexionMySQL conexion;
        ControladorUsuario controlador;
        
    public ControlAcceso() {
        initComponents();
        this.setLocationRelativeTo(null);
        
         conexion=new ConexionMySQL();
         controlador=new ControladorUsuario(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Control de Acceso");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear Cuenta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Recuperar contraseña");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         try{
            conexion.conectar();
            System.out.println("Conectado");
        }catch( SQLException ex){
           ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
             Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        boolean contraseñaCheck=false;
        String Usuario="";
        String Contraseña="";
        String Contraseña2="";
        String Respuesta="";
        
         Usuario=  JOptionPane.showInputDialog(rootPane,"Usuario", "Usuario nuevo", HEIGHT);
         
        while(contraseñaCheck==false){
           
            Contraseña=  JOptionPane.showInputDialog(rootPane,"Contraseña", "Contraseña nueva", HEIGHT);
            Contraseña2=  JOptionPane.showInputDialog(rootPane,"Confirmar Contraseña", "Confirmar Contraseña", HEIGHT);

            if(Contraseña.equals(Contraseña2)){
                contraseñaCheck=true;
            }else{
                JOptionPane.showMessageDialog(rootPane, "No coinciden introduzcalas de nuevo");
            }
            
        }
        
        Respuesta=  JOptionPane.showInputDialog(rootPane,"Pregunta seguridad", "Cual fue tu primera mascota?", HEIGHT);
        
         String consulta = "INSERT INTO `usuarios` (`Usuario`, `Contraseña`, `Respuesta`) VALUES ('"+Usuario+"','"+Contraseña+"','"+Respuesta+"');";
        try {
             conexion.ejecutarInsertDeleteUpdate(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            conexion.conectar();
            System.out.println("Conectado");
        }catch( SQLException ex){
           ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
             Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        boolean correcto=false;
        
        String Usuario="";
        String Respuesta="";
        String RespuestaConsulta="";
        String ContraseñaConsulta="";
        String consulta="";
        String consultaUsuario;
        
        ResultSet rset = null;
        int intentos=1;
        
        Usuario=  JOptionPane.showInputDialog(rootPane,"Usuario", "Escribe el usuario del que quieres recuperar la contraseña", HEIGHT);
        Respuesta=  JOptionPane.showInputDialog(rootPane,"Pregunta seguridad", "Cual fue tu primera mascota?", HEIGHT);
        
        while(correcto==false && intentos<=3){
  
            try {
                  consultaUsuario="SELECT Respuesta FROM `usuarios` where Usuario='"+Usuario+"';";
                rset = conexion.ejecutarSelect(consultaUsuario);
            } catch (SQLException ex) {
                Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if(rset.next()){
                RespuestaConsulta = rset.getString("Respuesta");
            }else{
                    JOptionPane.showMessageDialog(rootPane, "Usuario erroneo");
                    
                }
            } catch (SQLException ex) {
        
                Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
            }
                rset = null;
        if(Respuesta.equals(RespuestaConsulta)){
        
         consulta = "SELECT Contraseña FROM `usuarios` where Usuario='"+Usuario+"';";
         
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "respuesta incorrecta introducela de nuevo");
             Respuesta=  JOptionPane.showInputDialog(rootPane,"Pregunta seguridad", "Cual fue tu primera mascota?", HEIGHT);
             intentos=intentos+1;
        }
            try {
                
                rset = conexion.ejecutarSelect(consulta);
                if(rset.next()){
                ContraseñaConsulta = rset.getString("Contraseña");
                 JOptionPane.showMessageDialog(rootPane, "Contraseña: "+ContraseñaConsulta);
                 correcto=true;
                }else{
                 JOptionPane.showMessageDialog(rootPane, "error");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
            }
             if(intentos>=3){
                 JOptionPane.showMessageDialog(rootPane, "Usuario eliminado por bobo");
          consulta = "DELETE FROM usuarios where Usuario='"+Usuario+"';";
        try {
             conexion.ejecutarInsertDeleteUpdate(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            
          }
            
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        boolean correcto=false;
        String Usuario="";
        String Contraseña="";
        String consulta="";
        String ContraseñaConsulta="";
        ResultSet rset = null;
        Usuario=jTextField1.getText();
        Contraseña=jTextField2.getText();
                
        while(correcto==false){
        try{                   
             
             try{
                 conexion.conectar();
                 System.out.println("Conectado");
             }catch( SQLException ex){
                 ex.printStackTrace();
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
             }
             
          
             
             consulta = "SELECT Contraseña FROM `usuarios` where Usuario='"+Usuario+"';";
             rset = conexion.ejecutarSelect(consulta);
             
             if(rset.next()){
             ContraseñaConsulta = rset.getString("Contraseña");
             }
          
             if(ContraseñaConsulta.equals(Contraseña)){
                  JOptionPane.showMessageDialog(rootPane, "Contraseña Correcta");
                  correcto=true;
                  
                  AppMusica music= new AppMusica();
                 music.setSize(400,400);
                 music.setVisible(true);
                 
                 
             }else{
                  JOptionPane.showMessageDialog(rootPane, "Usuario u contraseña incorrecta");
                  Usuario=  JOptionPane.showInputDialog(rootPane,"Usuario", "Usuario", HEIGHT);
                  Contraseña=  JOptionPane.showInputDialog(rootPane,"Contraseña", "Contraseña", HEIGHT);
             }
             
             
         }catch( SQLException ex){
                Logger.getLogger(ControlAcceso.class.getName()).log(Level.SEVERE, null, ex);
                
        }
     }
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlAcceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
